### ISSUE TITLE
Configuration for monitor-repos should be moved to individual repos

### ISSUE THREAD

**Issue by TheKevJames** [TheKevJames/dead-simple-ops#11]
ie. change:

```
MyCoolGithubOrg:
    monitor-repos:
        repos:
            - MyCoolApp
            - MyEvenCoolerApp
            - MyTerribleApp
        branches:
            - develop
            - master
            - staging
            - production
        base-branch: develop
```

to

```
MyCoolApp:
    monitor-repos:
        branches:
            - develop
            - master
        base-branch: develop

MyEvenCoolerApp:
    monitor-repos:
        branches:
            - develop
            - master
            - staging
            - production
        base-branch: develop

MyTerribleApp:
    monitor-repos:
        branches:
            - master
            - production
        base-branch: master

MyCoolGithubOrg:
    monitor-repos:
        repos:
            - MyCoolApp
            - MyEvenCoolerApp
            - MyTerribleApp
```

to allow individual repo configuration. The org, then, effectively just becomes an alias; maybe do away with that entirely and call `monitor-repos MyCoolApp MyEvenCoolerApp MyTerribleApp ...`?
